### ISSUE TITLE
How to get the binary?

### ISSUE THREAD

**Issue by ittaiz** [geoff-addepar/heap-dump#4]
Hi,
I can't find any binary for this and when I try to open this project in intellij it's broken.
When I try to remove the faulty classpath entries ("tools and jdi" is one example) then still nothing builds.

**Comment by glywood** [comment]
The binary is available under the "releases" section on github. They don't make it easy to find, maybe I should put a link to it in the readme.

https://github.com/geoff-addepar/heap-dump/releases

**Comment by ittaiz** [comment]
Thanks! Indeed I couldn't find the tab in the UI so I thought you just had no relelases. Strange that github doesn't display the tab when there are releases.
